[api_keys]
openai_key = "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"


[assistant]
id = "asst_wGov148s16dwmjxHwQ0uXCqc"